name: perkfy
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  pin_code_fields: ^8.0.1
  percent_indicator: ^4.2.3
  flutter_slidable: ^1.2.0 # Check for the latest version on pub.dev
  qr_code_scanner: ^1.0.1
  permission_handler: ^10.0.0
  url_launcher: ^6.0.20

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: MetropolisMedium
      fonts:
        - asset: assets/font/metropolis/Metropolis-Medium.otf
    - family: RubikMedium
      fonts:
        - asset: assets/font/rubik/static/Rubik-Medium.ttf
